# Read the Docs configuration file for django-app-parameter
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      # Cancel building pull requests when a new commit is pushed
      - git fetch --unshallow || true
    post_install:
      # Install dependencies with poetry
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with dev

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Optionally build your docs in additional formats such as PDF and ePub
  formats:
    - pdf
    - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - method: pip
      path: .
