# Read the Docs configuration file for django-app-parameter
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # Optionally build your docs in additional formats such as PDF and ePub
  formats:
    - pdf
    - epub

# Install Python dependencies required for building documentation
python:
  install:
    # Install Sphinx and documentation dependencies
    - requirements: docs/requirements.txt
    # Install the package itself so autodoc can import it
    - method: pip
      path: .
